### ISSUE TITLE
Wrench Doesn't Work

### ISSUE THREAD

**Issue by ghost** [Necr0/ConvenientAdditions#14]
it rotates, it is working but dismantling doesn't work. tried on actually additions mods block. i just wanted to dismantle the block but i couldn't. i tried pressing shift + right click but no work. does it have another working style? or bug

**Comment by QbDesu** [comment]
As far as I can tell, Actually Additions doesn't actually provide any dismantling wrench itself. This means the blocks don't implemented the interfaces required for my wrench to function. In fact, it shouldn't be able to dismantle any machines other than my mod's own ones because it would require them to implement my interface, which is very unlikely to happen.

In case you are wondering, only very few mods actually still have wrenches that work on most other mods' blocks. Previously, the de facto standard was CoFHLib's "IDismantleabe"-interface. But when CoFHLib was discontinued(between 1.7.10 and 1.8) the code broke and modders started implementing their own solution. There is no real standard now. But if you tell me a mod, that already has a dismantling wrench in place, and want my wrenches to work with it, just tell me and I'll see what I can do.
(EnderIO won't work because of the way the dismantling is coded.)

**Comment by ghost** [comment]
hmmm... i just thought it should be easy :/ thanks.
