### ISSUE TITLE
Support for dense ores

### ISSUE THREAD

**Issue by illumincrotty** [Necr0/ConvenientAdditions#21]
When mining an ore vein with dense ores (https://github.com/rwtema/DenseOres) the adventurer's pick doesn't vein mine the dense ore. Even when I register the dense ore in the ore dictionary it doesn't vein mine it.

**Comment by QbDesu** [comment]
I think they share an OreDictionary entry and if I'm correct the changes I made to the flood filling algorithm should take care of that because it should now recognize them as part of the same vein. The new flood filling technique now checks for OreDictionary entries instead of blocks, so even ores from other mods could be included.
