### ISSUE TITLE
Crash on startup. Possibly lack of Baubles (not available for 1.11)

### ISSUE THREAD

**Issue by AndaleTheGreat** [Necr0/ConvenientAdditions#3]
http://pastebin.com/SzxFbU2A
Forge 13.19.0.2178
Convenient 1.0.12 build 16
The rest: http://i.imgur.com/nyMjn9T.png

**Comment by QbDesu** [comment]
My API folder was meant to be compiled into the mod but wasn't. I'll have to look into gradle a bit but it should be fixed in the next build.

**Comment by QbDesu** [comment]
I might release a quick and dirty fix tomorrow evening(UTC+1). Because I have already worked on some new features locally I gotta tie up some loose ends first. However, I should be able to do it easily after school tomorrow. For now I'll go to bed(11.39pm)

**Comment by tlitookilakin** [comment]
thank you for getting to the bottom of this :)
It is also an issue in the 1.10 version, though I don't know if you're still actively developing that version.

**Comment by QbDesu** [comment]
The [latest build(v.1.0.13-build20)](https://minecraft.curseforge.com/projects/convenient-additions/files) shouldn't throw any errors now. Tested in a clean Minecraft instance as well as with Baubles and JEI and should work for now. However, JEI integration for the Tome of Transmutation doesn't seem to be working as documented in #4. And no, I unfortunately will not maintain 1.10.2 anymore because of lack of time.

Anyways, I want to thank both of you for reporting the bug and I hope you have a nice day!
